export const countryNames = [
    { word: "la France", answer: "フランス" },
    { word: "l'Espagne", answer: "スペイン" },
    { word: "l'Italie", answer: "イタリア" },
    { word: "l'Allemagne", answer: "ドイツ" },
    { word: "le Royaume-Uni", answer: "イギリス" },
    { word: "l'Angleterre", answer: "イングランド" },
    { word: "la Grèce", answer: "ギリシャ" },
    { word: "le Portugal", answer: "ポルトガル" },
    { word: "la Belgique", answer: "ベルギー" },
    { word: "la Suisse", answer: "スイス" },
    { word: "le Luxembourg", answer: "ルクセンブルク" },
    { word: "les Pays-Bas", answer: "オランダ" },
    { word: "la Turquie", answer: "トルコ" },
    { word: "la Syrie", answer: "シリア" },
    { word: "Israël", answer: "イスラエル" },
    { word: "le Qatar", answer: "カタール" },
    { word: "Dubaï", answer: "ドバイ" },
    { word: "la Russie", answer: "ロシア" },
    { word: "l'Algérie", answer: "アルジェリア" },
    { word: "la Tunisie", answer: "チュニジア" },
    { word: "le Maroc", answer: "モロッコ" },
    { word: "l'Égypte", answer: "エジプト" },
    { word: "le Sénégal", answer: "セネガル" },
    { word: "la Côte d'Ivoire", answer: "コートジボワール" },
    { word: "le Congo", answer: "コンゴ" },
    { word: "l'Afrique du Sud", answer: "南アフリカ" },
    { word: "le Canada", answer: "カナダ" },
    { word: "le Québec", answer: "ケベック" },
    { word: "les États-Unis d'Amérique", answer: ["アメリカ合衆国", "アメリカガッシュウコク"] },
    { word: "le Mexique", answer: "メキシコ" },
    { word: "le Brésil", answer: "ブラジル" },
    { word: "l'Argentine", answer: "アルゼンチン" },
    { word: "le Chili", answer: "チリ" },
    { word: "l'Australie", answer: "オーストラリア" },
    { word: "l'Autriche", answer: "オーストリア" },
    { word: "la Nouvelle-Zélande", answer: "ニュージーランド" },
    { word: "Singapour", answer: "シンガポール" },
    { word: "l'Inde", answer: "インド" },
    { word: "la Thaïlande", answer: "タイ" },
    { word: "le Viêt Nam", answer: "ベトナム" },
    { word: "la Chine", answer: ["中国", "チュウゴク"] },
    { word: "la Corée du Sud", answer: ["韓国", "カンコク"] },
    { word: "le Japon", answer: ["日本", "ニホン", "ニッポン"] },
];

export default {
    list: countryNames,
    ref: "https://www.youtube.com/watch?v=l7T0cqOlcLk&t=0s",
}