export default [
    { word: "人",   answer: "ひと",   meaning: "Humain" },
    { word: "男",   answer: "おとこ",   meaning: "Homme" },
    { word: "女",   answer: "おんな",   meaning: "Femme" },
    { word: "子",   answer: "こ",   meaning: "Enfant" },
    { word: "日",   answer: "ひ",   meaning: "Soleil" },
    { word: "月",   answer: "つき",   meaning: "Lune" },
    { word: "時",   answer: "とき",   meaning: "Temps" },
    { word: "水",   answer: "みず",   meaning: "Eau" },
    { word: "火",   answer: "ひ",   meaning: "Feu" },
    { word: "土",   answer: "つち",   meaning: "Terre (matière)" },
    { word: "風",   answer: "かぜ",   meaning: "Vent" },
    { word: "空",   answer: "そら",   meaning: "Ciel" },
    { word: "山",   answer: "やま",   meaning: "Montagne" },
    { word: "川",   answer: "かわ",   meaning: "Rivière" },
    { word: "木",   answer: "き",   meaning: "Arbre" },
    { word: "花",   answer: "はな",   meaning: "Fleur" },
    { word: "雨",   answer: "あめ",   meaning: "Pluie" },
    { word: "雪",   answer: "ゆき",   meaning: "Neige" },
    { word: "金",   answer: ["かね", "おかね"],   meaning: "Argent, Monnaie" },
    { word: "刀",   answer: "かたな",   meaning: "Sabre" },
];